### ISSUE TITLE
Example DSL has a minor error

### ISSUE THREAD

**Issue by tmarrs** [nicolasdespres/respect#15]
The example DSL reads as follows:
schema = Respect::HashSchema.define do |s|
  s.string "name"
  s.integer "age", greater_than: 18
  s.string "homepage", format: :email
end

But there's a minor mistake that causes the schema validation to always return false.
The last value in the DSL should read:
  s.string "email", format: :email

Then the schema validation examples lower down the page work as advertised.

**Comment by nicolasdespres** [comment]
Thanks for reporting it. What a shamed for the first example :-(....
