### ISSUE TITLE
Main example needs a require statement

### ISSUE THREAD

**Issue by tmarrs** [nicolasdespres/respect#17]
Before using Respect, you need to require it. The first 2 lines should look like this:

require 'respect'

schema = Respect::HashSchema.define do |s|
...

That way, someone can just copy the code off the page, paste it directly into irb or rails console, and it just works out of the box.

**Comment by nicolasdespres** [comment]
This is part of the second section: "Getting started". I decided, like others projects do (for instance [rails/jbuilder](https://github.com/rails/jbuilder)), to first give the flavor of the project without bothering the reader with usual "infrastructure" code. Ruby's users are used to this command so there is nothing new for them here. I prefer to stay focus on the heart of the project in the first section. I admit that is debatable.
