### ISSUE TITLE
`puts JSON.pretty_generate(schema.to_h)` doesn't actually work

### ISSUE THREAD

**Issue by gjtorikian** [nicolasdespres/respect#18]
In Ruby 2.1, I get:

```
lib/respect/schema.rb:252:in `to_json': unknown format '#<JSON::Ext::Generator::State:0x007fd32b89b5d8>' (ArgumentError)
    from /opt/rubies/2.1.4-github1/lib/ruby/2.1.0/json/common.rb:285:in `generate'
    from /opt/rubies/2.1.4-github1/lib/ruby/2.1.0/json/common.rb:285:in `pretty_generate'
    from scheme.rb:11:in `<main>'
```

I think the `def to_json` implementation assumes some other value for `format`.

**Comment by gjtorikian** [comment]
Ah, I just noticed the part in the README where this is 1.9.3-compatible. Using `rbenv` to switch versions, I got everything working. :+1: 

Would be happy to help make this Ruby 2+ compatible. It's a nice little DSL and does everything necessary.

**Comment by nicolasdespres** [comment]
Sorry for replying that late.

I think it should not be difficult to make it Ruby 2+ compatible. In the meantime I changed my job and I no longer working with Ruby and Rails.
